language: python
sudo: false

addons:
  apt:
    packages:
    - unzip

env:
  - LUA="luajit=2.0"
  - LUA="luajit=2.0.3"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - mkdir -p "$PWD/.bin"
  - .travis-ci/download-glualint.sh "$PWD/.bin"
  - export PATH=$PATH:$PWD/lua_install/bin:$PWD/.bin # Add directory with all installed binaries to PATH

script:
  - .travis-ci/check-syntax.sh
  - glualint --config .glualint.json .

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: always
