language: python
sudo: false

addons:
  apt:
    packages:
    - unzip
    - lua5.1
    - luarocks

install:
  - luarocks install luacheck

script:
  - .travis-ci/check-syntax.sh "$TRAVIS_BUILD_DIR"
  - .travis-ci/luacheck.sh

after_script:
  - rm -rf "${BINDIR}"

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: always
