language: python
sudo: false

addons:
  apt:
    packages:
    - unzip

env:
  - LUA="luajit=2.0.3"
  - LUA="luajit=2.0"

before_install:
  - BINDIR="$(mktemp -d --suffix .bindir)"
  - pip install hererocks
  - hererocks "${BINDIR}" -r^ --$LUA
  - mkdir -p "${BINDIR}/bin"
  - .travis-ci/download-glualint.sh "${BINDIR}/bi"
  - export PATH=$PATH:${BINDIR}/bin # Add directory with all installed binaries to PATH

script:
  - .travis-ci/check-syntax.sh "$TRAVIS_BUILD_DIR"
  - glualint --config .glualint.json "$TRAVIS_BUILD_DIR"

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: always
