language: python
sudo: false

env:
  - LUA="5.1"

before_install:
  - BINDIR="$(mktemp -d --suffix .bindir)"
  - mkdir -p "${BINDIR}/bin"
  - hererocks "${BINDIR}" -r^ --lua "$LUA"
  - export PATH=$PATH:${BINDIR}/bin

install:
  - luarocks install luacheck

script:
  - .travis-ci/check-syntax.sh "$TRAVIS_BUILD_DIR"
  - .travis-ci/luacheck.sh

after_script:
  - rm -rf "${BINDIR}"

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: always
